In [1]:
from sklearn.datasets import load_files
import numpy as np

categories = ['01','02','03','04','07','08','09','10']
train = load_files('../aclImdb/train', categories=categories)
test = load_files('../aclImdb/test', categories=categories)

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(decode_error='replace', strip_accents='unicode',
                        stop_words='english', lowercase=True,
                        analyzer='word', ngram_range=(1,3),
                        use_idf=True, smooth_idf=True, sublinear_tf=True)

train_X = tfidf.fit_transform(train.data, train.target)
test_X = tfidf.transform(test.data)

train_y = train.target
test_y = test.target

In [3]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(train_X, train_y)
predicted = clf.predict(test_X)

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

predicted = np.clip(np.round(predicted), 0, 7)
diff = np.abs(test_y - predicted)
print np.mean(test_y == predicted)
print np.mean(diff <= np.ones(len(diff)))
print np.mean(diff <= 2*np.ones(len(diff)))
print confusion_matrix(test_y, predicted)

0.32528
0.67944
0.88644
[[2495  973  805  474  198   56   11   10]
 [ 781  522  453  316  156   60   11    3]
 [ 509  499  642  532  247   83   21    8]
 [ 280  394  629  661  422  191   45   13]
 [   5   33  129  310  581  628  402  219]
 [   3   15   68  240  531  762  654  577]
 [   3   11   38  130  358  571  551  682]
 [   2   24   66  228  565 1007 1189 1918]]
